### ISSUE TITLE
Replace filler Text

### ISSUE THREAD

**Issue by Anzenith** [Spheroman/ThingRanker#37]
On the Homepage, there is two descriptions, HOW IT WORKS and WHY PAIRWISE.
 Please write a proper description for both.

**Comment by Clolulu** [comment]
This website acts as a competition management system. You can create and configure competitions by setting up entries, ranking systems, and adding participants. The system tracks matchups between participants, with users selecting winners through a pairing page. Rankings are then automatically generated based on these results, allowing you to view the competition's progress and final outcome.

**Comment by Clolulu** [comment]
This competition management system utilizes a pairwise comparison approach for matchups. Instead of having users rank all participants at once, they progressively choose winners between two presented entries in the pairing page. This simplifies the process for users and focuses on direct comparisons. The system leverages these pairwise wins and losses to automatically calculate Glicko-2 ratings, a ranking system well-suited for competitions where the number of participants is manageable and not too large. This approach ensures efficient ranking determination while keeping user interaction straightforward.

**Comment by Spheroman** [comment]
> This competition management system utilizes a pairwise comparison approach for matchups. Instead of having users rank all participants at once, they progressively choose winners between two presented entries in the pairing page. This simplifies the process for users and focuses on direct comparisons. The system leverages these pairwise wins and losses to automatically calculate Glicko-2 ratings, a ranking system well-suited for competitions where the number of participants is manageable and not too large. This approach ensures efficient ranking determination while keeping user interaction straightforward.

This is ai generated, isn't it? Please either write it yourself or let someone else write it, as I don't want AI in our project.

**Comment by Clolulu** [comment]
HOW IT WORKS
This website allows the user to create a competition and rank the things. For example, when the user creates a competition (e.g.: favorite colors) participants can add their own favorite color, then when the admin press "start", participants will have to choose between two options, two alternatives at a time, until all the options are eliminated, then the result will be shown.

WHY PAIRWISE
Because it is easier for user to choose between 2 options. It simplifies and improves the accuracy of your decision-making.
